modLoader="javafml"
loaderVersion="[44,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/NertzhulDEV/creepy-creepers/issues"

[[mods]]
modId="creepycreepers"
version="${file.jarVersion}"
displayName="Creepy Creepers"
updateJSONURL="https://raw.githubusercontent.com/NertzhulDEV/creepy-creepers/dev/updates.json"
displayURL="https://curseforge.com/minecraft/mc-mods/creepy-creepers"
credits="KiriCattus, Paint_Ninja"
authors="Nertzhul"
description='''
Creepers be creepin!
'''

[[dependencies.creepycreepers]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"

[[dependencies.creepycreepers]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
