modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/NertzhulDEV/creepy-creepers/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://www.nertzhul.dev/mods/creepy-creepers/updates.json"
displayURL="https://curseforge.com/minecraft/mc-mods/creepy-creepers"
credits="KiriCattus, Paint_Ninja"
authors="Nertzhul"
description='''
Creepers be creepin!
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[46.0.14,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
